# Generated by Django 5.0.2 on 2024-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_alter_product_image_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_details',
            field=models.CharField(max_length=15000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_selling',
            field=models.BooleanField(default=False),
        ),
    ]
