# Generated by Django 5.0.2 on 2024-04-04 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_product_product_details_product_is_top_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
